version: '2'
services:
    rethinkdb-mongodb:
        container_name: rethinkdb-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/rethinkdb/mongodb/:/data/db/
